const fs = require("fs");
const path = require("path");
const { optimize } = require("svgo");

const SVG_DIR = path.join(__dirname, "../svg");
const OUTPUT_FILE = path.join(__dirname, "../icons.css");

// ⚠️ Uses @latest — always resolves to the newest GitHub Release
const CDN_BASE =
  "https://cdn.jsdelivr.net/gh/JacobMire/icon-library@latest/svg";

// ✅ Validate SVG
function validateSVG(content, file) {
  if (!content.includes("<svg")) throw new Error(`${file} is not a valid SVG`);
  if (!content.includes("viewBox")) throw new Error(`${file} missing viewBox`);
}

// ✅ Normalize prefix + optimize all SVGs in place
function processSVGs() {
  const files = fs.readdirSync(SVG_DIR);

  files.forEach((file) => {
    if (!file.endsWith(".svg")) return;

    let filePath = path.join(SVG_DIR, file);

    // Normalize prefix (handles ez-ez-* duplicates)
    const normalized = "ez-" + file.replace(/^ez-+/, "");
    const newPath = path.join(SVG_DIR, normalized);

    if (file !== normalized) {
      fs.renameSync(filePath, newPath);
      filePath = newPath;
      console.log(`Renamed: ${file} → ${normalized}`);
    }

    const svg = fs.readFileSync(filePath, "utf-8");
    validateSVG(svg, normalized);

    const result = optimize(svg, {
      multipass: true,
      plugins: ["removeDimensions", "removeComments", "removeMetadata"],
    });

    fs.writeFileSync(filePath, result.data);
  });
}

// ✅ Generate CSS — single flat file, no @import indirection
function generateCSS() {
  const files = fs
    .readdirSync(SVG_DIR)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  let css = `/* Generated by build-icons — do not edit manually */

.ez-icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  background-color: currentColor;
  -webkit-mask-size: contain;
  mask-size: contain;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
}\n`;

  files.forEach((file) => {
    const className = file.replace(".svg", "").replace(/^ez-/, "");
    css += `
.ez-icon-${className} {
  -webkit-mask-image: url("${CDN_BASE}/${file}");
  mask-image: url("${CDN_BASE}/${file}");
}\n`;
  });

  return css;
}

// 🚀 Run pipeline
function run() {
  processSVGs();
  const css = generateCSS();
  fs.writeFileSync(OUTPUT_FILE, css);
  console.log("✅ Build complete → icons.css");
}

run();
