const fs = require("fs");
const path = require("path");
const { optimize } = require("svgo");

const SVG_DIR = path.join(__dirname, "../svg");
const HOST = process.env.HOST || "admin.eazyiot.com";
const ORG = process.env.ORG || "";
// Output file logic:
let cssFileName = "icons.css";
if (HOST !== "admin.eazyiot.com" && ORG) {
  cssFileName = `${HOST}${ORG}icons.css`;
}
const OUTPUT_FILE = path.join(__dirname, "../", cssFileName);

// SVGs are served from jsDelivr at a pinned tag (fast, cached forever — fine because SVGs never change)
// icons.css is served from GitHub Pages (always fresh, no CDN tag-resolution caching)
const TAG = process.env.TAG || "latest";
const CDN_BASE = `https://cdn.jsdelivr.net/gh/JacobMire/icon-library@${TAG}/svg`;

function validateSVG(content, file) {
  if (!content.includes("<svg")) throw new Error(`${file} is not a valid SVG`);
  if (!content.includes("viewBox")) throw new Error(`${file} missing viewBox`);
}

function processSVGs() {
  const files = fs.readdirSync(SVG_DIR);

  files.forEach((file) => {
    if (!file.endsWith(".svg")) return;

    let filePath = path.join(SVG_DIR, file);

    const normalized = "ez-" + file.replace(/^ez-+/, "");
    const newPath = path.join(SVG_DIR, normalized);

    if (file !== normalized) {
      fs.renameSync(filePath, newPath);
      filePath = newPath;
      console.log(`Renamed: ${file} → ${normalized}`);
    }

    const svg = fs.readFileSync(filePath, "utf-8");
    validateSVG(svg, normalized);

    const result = optimize(svg, {
      multipass: true,
      plugins: ["removeDimensions", "removeComments", "removeMetadata"],
    });

    fs.writeFileSync(filePath, result.data);
  });
}

function generateCSS() {
  const files = fs
    .readdirSync(SVG_DIR)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  let css = `/* Generated by build-icons — do not edit manually */
/* SVG tag: ${TAG} */

.ez-icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  background-color: currentColor;
  -webkit-mask-size: contain;
  mask-size: contain;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
}\n`;

  files.forEach((file) => {
    const className = file.replace(".svg", "").replace(/^ez-/, "");
    css += `
.ez-icon-${className} {
  -webkit-mask-image: url("${CDN_BASE}/${file}");
  mask-image: url("${CDN_BASE}/${file}");
}\n`;
  });

  return css;
}

function run() {
  processSVGs();
  const css = generateCSS();
  fs.writeFileSync(OUTPUT_FILE, css);
  console.log(`✅ Build complete → icons.css (SVG tag: ${TAG})`);
}

run();
